{% set name = "amaranth" %}
{% set version = "0.5.4" %}
{% set sha256 = "9af1bf415ce41f6e97f95d66e30c8bbf6f551d6628962fb44afecec0a7a35b45" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/amaranth-lang/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation
  script_env:
    - PDM_BUILD_SCM_VERSION={{ version }}
  entry_points:
    - amaranth-rpc = amaranth.rpc:main
requirements:
  host:
    - python >=3.8
    - pip
    - pdm-backend
  run:
    - python >=3.8
    - importlib-metadata
    - importlib_resources
    - pyvcd >=0.2.2,<0.5
    - jinja2
    - jschon

test:
  imports:
    - amaranth
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/amaranth-lang/amaranth
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A modern hardware definition language and toolchain based on Python
  description: A modern hardware definition language and toolchain based on Python
  dev_url: https://github.com/amaranth-lang/amaranth

extra:
  recipe-maintainers:
    - whitequark
    - timkpaine
