{% set name = "amaranth" %}
{% set version = "0.3" %}
{% set sha256 = "102ca5e6b80c9c379e355c5e1c57263cba7be1c9cd0a58046568b427c1c977a1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/amaranth-lang/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - patches/0001-fix-extras.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  entry_points:
    - amaranth-rpc = amaranth.rpc:main
    - nmigen-rpc = nmigen.rpc:main
requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >=3.7
    - importlib_metadata
    - importlib_resources
    - pyvcd >=0.2.2,<0.4
    - jinja2

test:
  imports:
    - amaranth
    - nmigen 

about:
  home: https://github.com/amaranth-lang/amaranth
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A modern hardware definition language and toolchain based on Python
  description: A modern hardware definition language and toolchain based on Python
  dev_url: https://github.com/amaranth-lang/amaranth

extra:
  recipe-maintainers:
    - timkpaine
