{% set name = "amaranth" %}
{% set version = "0.4.0" %}
{% set sha256 = "f377c113af9d6772331509fff72cf19d060cd16849981ce32b6eeb94d64c62eb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/amaranth-lang/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  entry_points:
    - amaranth-rpc = amaranth.rpc:main
    - nmigen-rpc = nmigen.rpc:main
requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >=3.7
    - importlib_metadata
    - importlib_resources
    - pyvcd >=0.2.2,<0.4
    - jinja2

test:
  imports:
    - amaranth
    - nmigen

about:
  home: https://github.com/amaranth-lang/amaranth
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A modern hardware definition language and toolchain based on Python
  description: A modern hardware definition language and toolchain based on Python
  dev_url: https://github.com/amaranth-lang/amaranth

extra:
  recipe-maintainers:
    - whitequark
    - timkpaine
