{% set name = "amaranth" %}
{% set version = "0.4.5" %}
{% set sha256 = "913c2a13274caed077dcdce61ae375ca0b35ad683dd4e615c59ea5bee69cb6b9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/amaranth-lang/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv --no-deps
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  entry_points:
    - amaranth-rpc = amaranth.rpc:main
requirements:
  host:
    - python >=3.8
    - pip
    - pdm-backend
  run:
    - python >=3.8
    - importlib_metadata
    - importlib_resources
    - pyvcd >=0.2.2,<0.5
    - jinja2

test:
  imports:
    - amaranth

about:
  home: https://github.com/amaranth-lang/amaranth
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A modern hardware definition language and toolchain based on Python
  description: A modern hardware definition language and toolchain based on Python
  dev_url: https://github.com/amaranth-lang/amaranth

extra:
  recipe-maintainers:
    - whitequark
    - timkpaine
